name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run -e esp32dev

      - name: Check PlatformIO Project
        run: pio check --skip-packages --fail-on-defect medium --fail-on-defect high -e esp32dev -f src

      - name: Unit Test PlatformIO Project
        run: pio test -e native
